baseURL = "https://happysxpp.github.io/"
author = "happyxpp"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# Above are configs from hugoBasicExample

title = "HAPPYXPP'S BLOG"
theme = "hugo-primer"
hasCJKLanguage = true
summaryLength = 10
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-12345678-0"
disqusShortname=""
#copyright = "&copy;happyxpp 2022-"
enableEmoji = true

[params]
description = "HappyXpp Blog"
twitter = ""
useIcon = false
useTwitterCard = true
# exampleSite must not have js share widget: #36
shareTo = ["Twitter", "Hatena", "Facebook", "Pocket"]
showFooterCredits = true
math = true

